# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name              = 'glpp'
author            = 'Fabian Jung'
description       = 'An OpenGL Wrapper library for modern C++.'
cpp               = 20
github            = 'fabian-jung/glpp'
private_repo      = false
license           = [ 'MIT', 'https://github.com/fabian-jung/glpp/blob/master/LICENSE' ]
show_includes     = false
logo              = 'doc/images/favicon-dark.svg'
favicon           = 'doc/images/favicon.svg'
navbar            = [ 'namespaces', 'classes' ]
theme             = 'dark'
generate_tagfile  = true
#scripts           = []


[warnings]
enabled           = true
# treat_as_errors = true
undocumented      = true

[sources]
paths             = [ 'doc/pages' ]
recursive_paths   = [ 'modules', 'doc/modules' ]
patterns          = [ '*.h', '*.hpp', '*.dox' ]
# strip_paths       = [ '../include' ]
extract_all = true


[images]
paths             = [ 'doc/images' ]

# [macros]
# [meta_tags]
# [code_blocks]

[badges]
'1. C++20'        = [
    'badge-C++20.svg',
    'https://en.cppreference.com/w/cpp/compiler_support'
 ]
'2. Github Actions'     = [
    'https://img.shields.io/github/workflow/status/fabian-jung/glpp/Ubuntu%20Platform%20Test/master?label=build&logo=Github%20Actions&logoColor=%23ffffff',
    'https://github.com/fabian-jung/glpp/actions'
]

# [autolinks]