name: Documentation build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Pull ubuntu runtime container
      run: |
        docker pull ghcr.io/fabian-jung/glpp/build-ubuntu:latest
        
    - name: build
      run: |
        mkdir build
        docker run --mount src="$(pwd)",target=/glpp,type=bind --mount src="$(pwd)/build",target=/build,type=bind ghcr.io/fabian-jung/glpp/build-ubuntu:latest doc
    
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build/html