name: Native Test

on:
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: ReleaseWithDebInfo

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: "Install Dependencies"
      run: |
        sudo apt-get install g++ cmake git make ninja-build 
        # vcpkg
        sudo apt-get install curl zip unzip tar pkg-config python3.10-venv flex bison
        # glew
        sudo apt-get install libxmu-dev libxi-dev libgl-dev
        # glfw
        sudo apt-get install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
        # glpp
        sudo apt-get install libopengl-dev blender libegl-dev

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/vendor/vcpkg'

    - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: 'vcpkg'
        buildPreset: 'all-vcpkg'
        testPreset: 'all-vcpkg'