name: Ubuntu Platform Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        os: [ubuntu]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull ubuntu runtime container
      run: |
        docker pull ghcr.io/fabian-jung/glpp/build-${{ matrix.os }}:latest
        
    - name: build and test
      run: |
        docker run --mount src="$(pwd)",target=/glpp,type=bind,readonly gitfabianj/glpp-ubuntu:latest test ${{ matrix.compiler }}