#pragma once

#include "core/glpp.hpp"
#include "core/object/attribute_properties.hpp"
#include "core/object/buffer.hpp"
#include "core/object/shader.hpp"
#include "core/object/texture.hpp"
#include "core/object/vertex_array.hpp"
#include "core/object/framebuffer.hpp"
#include "core/object/texture_atlas.hpp"
#include "core/object/shader_factory.hpp"
#include "core/render/model.hpp"
#include "core/render/renderer.hpp"
#include "core/render/view.hpp"
#include "core/render/camera.hpp"
#include "core/render/light.hpp"
